# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
   "iPhone 16",
 ])

languages([
   "en",
   "zh-Hans",
   "fr",
   "de",
   "ja",
   "ru",
   "es",
   "it"
 ])

# The name of the scheme which contains the UI Tests
scheme("GrainFastlaneSnapshots")

